# Generated by Django 5.2.11 on 2026-02-06 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contabilidad', '0001_initial'),
        ('operaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operaciones.cliente'),
        ),
        migrations.AddField(
            model_name='factura',
            name='contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operaciones.contrato'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operaciones.contrato'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='cuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contabilidad.cuenta'),
        ),
        migrations.AddField(
            model_name='relacioncentrocosto',
            name='centro_costo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contabilidad.centrocosto'),
        ),
        migrations.AddField(
            model_name='relacioncentrocosto',
            name='movimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.movimiento'),
        ),
    ]
