from django.urls import path

from .views import (
    CertificacionCreateView,
    CertificacionDeleteView,
    CertificacionListView,
    CertificacionUpdateView,
    ContactoEmergenciaCreateView,
    ContactoEmergenciaDeleteView,
    ContactoEmergenciaListView,
    ContactoEmergenciaUpdateView,
    DashboardView,
    DocumentoEmpleadoCreateView,
    DocumentoEmpleadoDeleteView,
    DocumentoEmpleadoListView,
    DocumentoEmpleadoUpdateView,
    EmpleadoCertificacionCreateView,
    EmpleadoCertificacionDeleteView,
    EmpleadoCertificacionListView,
    EmpleadoCertificacionUpdateView,
    EmpleadoCreateView,
    EmpleadoDeleteView,
    EmpleadoListView,
    EmpleadoUpdateView,
    PuestoCreateView,
    PuestoDeleteView,
    PuestoListView,
    PuestoUpdateView,
    TurnoCreateView,
    TurnoDeleteView,
    TurnoListView,
    TurnoUpdateView,
    UserCreateView,
    UserDeleteView,
    UserEmpleadoCreateView,
    UserListView,
    UserUpdateView,
    GroupCreateView,
    GroupDeleteView,
    GroupListView,
    GroupUpdateView,
    PerfilView,
    AsignacionesHistoriaView,
)

app_name = "usuarios"

urlpatterns = [
    path("", DashboardView.as_view(), name="dashboard"),
    path("perfil/", PerfilView.as_view(), name="perfil"),
    path("perfil/asignaciones/", AsignacionesHistoriaView.as_view(), name="perfil_asignaciones"),
    path("accesos/", UserListView.as_view(), name="user_list"),
    path("accesos/nuevo/", UserCreateView.as_view(), name="user_create"),
    path("accesos/nuevo-empleado/", UserEmpleadoCreateView.as_view(), name="user_empleado_create"),
    path("accesos/<int:pk>/editar/", UserUpdateView.as_view(), name="user_update"),
    path("accesos/<int:pk>/eliminar/", UserDeleteView.as_view(), name="user_delete"),
    path("grupos/", GroupListView.as_view(), name="group_list"),
    path("grupos/nuevo/", GroupCreateView.as_view(), name="group_create"),
    path("grupos/<int:pk>/editar/", GroupUpdateView.as_view(), name="group_update"),
    path("grupos/<int:pk>/eliminar/", GroupDeleteView.as_view(), name="group_delete"),
    path("puestos/", PuestoListView.as_view(), name="puesto_list"),
    path("puestos/nuevo/", PuestoCreateView.as_view(), name="puesto_create"),
    path("puestos/<int:pk>/editar/", PuestoUpdateView.as_view(), name="puesto_update"),
    path("puestos/<int:pk>/eliminar/", PuestoDeleteView.as_view(), name="puesto_delete"),
    path("turnos/", TurnoListView.as_view(), name="turno_list"),
    path("turnos/nuevo/", TurnoCreateView.as_view(), name="turno_create"),
    path("turnos/<int:pk>/editar/", TurnoUpdateView.as_view(), name="turno_update"),
    path("turnos/<int:pk>/eliminar/", TurnoDeleteView.as_view(), name="turno_delete"),
    path("empleados/", EmpleadoListView.as_view(), name="empleado_list"),
    path("empleados/nuevo/", EmpleadoCreateView.as_view(), name="empleado_create"),
    path("empleados/<int:pk>/editar/", EmpleadoUpdateView.as_view(), name="empleado_update"),
    path("empleados/<int:pk>/eliminar/", EmpleadoDeleteView.as_view(), name="empleado_delete"),
    path("certificaciones/", CertificacionListView.as_view(), name="certificacion_list"),
    path(
        "certificaciones/nuevo/",
        CertificacionCreateView.as_view(),
        name="certificacion_create",
    ),
    path(
        "certificaciones/<int:pk>/editar/",
        CertificacionUpdateView.as_view(),
        name="certificacion_update",
    ),
    path(
        "certificaciones/<int:pk>/eliminar/",
        CertificacionDeleteView.as_view(),
        name="certificacion_delete",
    ),
    path(
        "empleados-certificaciones/",
        EmpleadoCertificacionListView.as_view(),
        name="empleado_certificacion_list",
    ),
    path(
        "empleados-certificaciones/nuevo/",
        EmpleadoCertificacionCreateView.as_view(),
        name="empleado_certificacion_create",
    ),
    path(
        "empleados-certificaciones/<int:pk>/editar/",
        EmpleadoCertificacionUpdateView.as_view(),
        name="empleado_certificacion_update",
    ),
    path(
        "empleados-certificaciones/<int:pk>/eliminar/",
        EmpleadoCertificacionDeleteView.as_view(),
        name="empleado_certificacion_delete",
    ),
    path(
        "documentos/",
        DocumentoEmpleadoListView.as_view(),
        name="documento_empleado_list",
    ),
    path(
        "documentos/nuevo/",
        DocumentoEmpleadoCreateView.as_view(),
        name="documento_empleado_create",
    ),
    path(
        "documentos/<int:pk>/editar/",
        DocumentoEmpleadoUpdateView.as_view(),
        name="documento_empleado_update",
    ),
    path(
        "documentos/<int:pk>/eliminar/",
        DocumentoEmpleadoDeleteView.as_view(),
        name="documento_empleado_delete",
    ),
    path(
        "contactos/",
        ContactoEmergenciaListView.as_view(),
        name="contacto_emergencia_list",
    ),
    path(
        "contactos/nuevo/",
        ContactoEmergenciaCreateView.as_view(),
        name="contacto_emergencia_create",
    ),
    path(
        "contactos/<int:pk>/editar/",
        ContactoEmergenciaUpdateView.as_view(),
        name="contacto_emergencia_update",
    ),
    path(
        "contactos/<int:pk>/eliminar/",
        ContactoEmergenciaDeleteView.as_view(),
        name="contacto_emergencia_delete",
    ),
]
