# Generated by Django 5.2.11 on 2026-02-06 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activos', '0002_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('fecha', models.DateField()),
                ('resultado', models.CharField(max_length=80)),
                ('observaciones', models.TextField(blank=True)),
                ('content_type', models.ForeignKey(limit_choices_to=models.Q(('app_label', 'activos'), ('model__in', ['vehiculo', 'armamento'])), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('realizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('fecha_apertura', models.DateField()),
                ('fecha_cierre', models.DateField(blank=True, null=True)),
                ('estatus', models.CharField(choices=[('abierta', 'Abierta'), ('en_proceso', 'En proceso'), ('cerrada', 'Cerrada')], default='abierta', max_length=20)),
                ('motivo', models.TextField(blank=True)),
                ('costo_mano_obra', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('observaciones', models.TextField(blank=True)),
                ('content_type', models.ForeignKey(limit_choices_to=models.Q(('app_label', 'activos'), ('model__in', ['vehiculo', 'armamento'])), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('costo_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('refaccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activos.refaccion')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantenimiento.ordenmantenimiento')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramacionMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('frecuencia_km', models.PositiveIntegerField(default=0)),
                ('frecuencia_dias', models.PositiveIntegerField(default=0)),
                ('proximo_servicio', models.DateField(blank=True, null=True)),
                ('activo_registro', models.BooleanField(default=True)),
                ('content_type', models.ForeignKey(limit_choices_to=models.Q(('app_label', 'activos'), ('model__in', ['vehiculo', 'armamento'])), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
