# Generated by Django 5.2.11 on 2026-02-06 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=160)),
                ('rfc', models.CharField(blank=True, max_length=13)),
                ('contacto_principal', models.CharField(blank=True, max_length=120)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('direccion', models.TextField(blank=True)),
                ('estatus', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('cerrado', 'Cerrado')], default='activo', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True)),
                ('requiere_armamento', models.BooleanField(default=False)),
                ('requiere_vehiculo', models.BooleanField(default=False)),
                ('requiere_canino', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=40, unique=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('estatus', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('cerrado', 'Cerrado')], default='activo', max_length=20)),
                ('condiciones', models.TextField(blank=True)),
                ('tarifa_base', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operaciones.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Sitio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=160)),
                ('tipo', models.CharField(blank=True, max_length=80)),
                ('direccion', models.TextField()),
                ('ciudad', models.CharField(blank=True, max_length=80)),
                ('estado', models.CharField(blank=True, max_length=80)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('estatus', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('cerrado', 'Cerrado')], default='activo', max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operaciones.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Requerimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_guardias', models.PositiveIntegerField(default=0)),
                ('cantidad_caninos', models.PositiveIntegerField(default=0)),
                ('vehiculos_requeridos', models.PositiveIntegerField(default=0)),
                ('armamento_requerido', models.PositiveIntegerField(default=0)),
                ('horario', models.CharField(blank=True, max_length=120)),
                ('observaciones', models.TextField(blank=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operaciones.contrato')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operaciones.servicio')),
                ('sitio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operaciones.sitio')),
            ],
        ),
        migrations.CreateModel(
            name='Incidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('tipo', models.CharField(max_length=80)),
                ('descripcion', models.TextField()),
                ('severidad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], default='baja', max_length=20)),
                ('estatus', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('cerrado', 'Cerrado')], default='activo', max_length=20)),
                ('evidencia', models.FileField(blank=True, upload_to='operaciones/incidente_evidencias/')),
                ('reportado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.empleado')),
                ('sitio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operaciones.sitio')),
            ],
        ),
    ]
