# Generated by Django 5.2.11 on 2026-02-06 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(blank=True, max_length=80)),
                ('plataforma', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('web', 'Web')], max_length=20)),
                ('token_push', models.CharField(blank=True, max_length=255)),
                ('estatus', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=20)),
                ('ultimo_ping', models.DateTimeField(blank=True, null=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='PermisoGPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otorgado', models.BooleanField(default=True)),
                ('fecha_otorgado', models.DateTimeField(auto_now_add=True)),
                ('revocado', models.BooleanField(default=False)),
                ('fecha_revocado', models.DateTimeField(blank=True, null=True)),
                ('motivo', models.CharField(blank=True, max_length=200)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('bateria', models.PositiveSmallIntegerField(default=0)),
                ('timestamp', models.DateTimeField()),
                ('precision', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('origen', models.CharField(choices=[('app', 'App'), ('web', 'Web')], default='app', max_length=20)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.dispositivo')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.empleado')),
            ],
            options={
                'indexes': [models.Index(fields=['timestamp'], name='tracking_ub_timesta_6755dd_idx')],
            },
        ),
    ]
