# Generated by Django 5.2.11 on 2026-02-06 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asignaciones', '0001_initial'),
        ('operaciones', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operaciones.contrato'),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='sitio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operaciones.sitio'),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='turno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.turno'),
        ),
        migrations.AddField(
            model_name='asignacionempleado',
            name='asignacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asignaciones.asignacion'),
        ),
        migrations.AddField(
            model_name='asignacionempleado',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.empleado'),
        ),
        migrations.AddField(
            model_name='bitacoraasignacion',
            name='asignacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asignaciones.asignacion'),
        ),
        migrations.AddField(
            model_name='bitacoraasignacion',
            name='reportado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.empleado'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.empleado'),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='equipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='asignaciones.equipo'),
        ),
        migrations.AddField(
            model_name='asignacion',
            name='ruta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='asignaciones.ruta'),
        ),
    ]
