# Generated by Django 5.2.11 on 2026-02-07 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaciones', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RutaPunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=1)),
                ('nombre', models.CharField(max_length=120)),
                ('km_desde_anterior', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntos', to='asignaciones.ruta')),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
    ]
