# Generated by Django 5.2.11 on 2026-02-06 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Armamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=40, unique=True)),
                ('tipo', models.CharField(max_length=80)),
                ('marca', models.CharField(blank=True, max_length=80)),
                ('modelo', models.CharField(blank=True, max_length=80)),
                ('calibre', models.CharField(blank=True, max_length=40)),
                ('numero_serie', models.CharField(blank=True, max_length=60)),
                ('estatus', models.CharField(choices=[('activo', 'Activo'), ('mantenimiento', 'Mantenimiento'), ('baja', 'Baja')], default='activo', max_length=20)),
                ('fecha_alta', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AsignacionActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('estatus', models.CharField(choices=[('activo', 'Activo'), ('mantenimiento', 'Mantenimiento'), ('baja', 'Baja')], default='activo', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Combustible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=40)),
                ('unidad', models.CharField(default='litro', max_length=20)),
                ('costo_promedio', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='InventarioMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('ajuste', 'Ajuste')], max_length=20)),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('costo_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fecha', models.DateTimeField()),
                ('referencia', models.CharField(blank=True, max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Refaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('tipo_activo', models.CharField(choices=[('vehiculo', 'Vehiculo'), ('armamento', 'Armamento')], max_length=20)),
                ('unidad', models.CharField(max_length=20)),
                ('stock_minimo', models.PositiveIntegerField(default=0)),
                ('costo_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fecha_alta', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroCombustible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('litros', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('km', models.PositiveIntegerField(default=0)),
                ('proveedor', models.CharField(blank=True, max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=40, unique=True)),
                ('marca', models.CharField(max_length=80)),
                ('modelo', models.CharField(max_length=80)),
                ('anio', models.PositiveIntegerField()),
                ('placas', models.CharField(blank=True, max_length=20)),
                ('serie', models.CharField(blank=True, max_length=40)),
                ('tipo', models.CharField(blank=True, max_length=60)),
                ('capacidad', models.CharField(blank=True, max_length=60)),
                ('estatus', models.CharField(choices=[('activo', 'Activo'), ('mantenimiento', 'Mantenimiento'), ('baja', 'Baja')], default='activo', max_length=20)),
                ('km_actual', models.PositiveIntegerField(default=0)),
                ('fecha_alta', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
