# Generated by Django 5.2.11 on 2026-02-06 22:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activos', '0001_initial'),
        ('asignaciones', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionactivo',
            name='asignacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asignaciones.asignacion'),
        ),
        migrations.AddField(
            model_name='asignacionactivo',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(('app_label', 'activos'), ('model__in', ['vehiculo', 'armamento'])), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='inventariomovimiento',
            name='realizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventariomovimiento',
            name='refaccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activos.refaccion'),
        ),
        migrations.AddField(
            model_name='registrocombustible',
            name='autorizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registrocombustible',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activos.vehiculo'),
        ),
    ]
